version: '3.8'
services:
  user-service:
    build: ./userms
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  device-service:
    build: ./devicems
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: premianta
      POSTGRES_DB: mydatabase2
    networks:
      - microservices-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data:
