version: '3'

services:
  react:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND=172.30.0.2
      - CHOKIDAR_USEPOLLING=true
    networks:
      demo_net:
        ipv4_address: 172.30.0.10

networks:
  demo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
